In [1]:
### numpy , pandas 

In [ ]:
pip install numpy

In [2]:
import numpy as np

In [6]:
x = [1,2,3,4,5]

type(x)

list

In [7]:
x

[1, 2, 3, 4, 5]

In [56]:
### converting a list to numpy array

arr = np.array(x)
arr

array([1, 2, 3, 4, 5])

In [11]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
y = [1,2,3,4.5]
y

[1, 2, 3, 4.5]

In [16]:
arr2 = np.array(y)

In [18]:
arr2

array([1. , 2. , 3. , 4.5])

In [17]:
arr2.dtype

dtype('float64')

In [19]:
z = [1,2,3,"deji"]
z

[1, 2, 3, 'deji']

In [21]:
arr3 = np.array(z)
arr3

array(['1', '2', '3', 'deji'], dtype='<U11')

In [22]:
arr3.dtype

dtype('<U11')

In [23]:
### working with numpy

In [24]:
arr4 = np.array([1,2,3,4,5,6,7,8])

In [29]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
arr4.size

8

In [27]:
arr4.shape

(8,)

In [30]:
arr4.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
### performance some mathematical operation



In [33]:
arr4 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr4 * 10 

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
arr4 - 1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
arr4 / 6

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333,
       1.        , 1.16666667, 1.33333333])

In [38]:
type(arr4)

numpy.ndarray

In [39]:
arr4.dtype

dtype('int32')

In [37]:
#### boolean index

In [40]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr4 > 2

array([False, False,  True,  True,  True,  True,  True,  True])

In [45]:
arr4[arr4 > 2]### to get value where array 4  is greater than 2

array([3, 4, 5, 6, 7, 8])

In [46]:
arr4 < 5

array([ True,  True,  True,  True, False, False, False, False])

In [47]:
arr4[arr4 < 5] ### to get value where array 4  is less than 5

array([1, 2, 3, 4])

In [48]:
### statistics with numpy

In [49]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
arr4.mean()

4.5

In [54]:
arr4.var()

5.25

In [55]:
arr4.std()

2.29128784747792

In [ ]:
### pandas 
### two datatype >>> Series , DataFrame