In [5]:
import pandas as pd
import numpy as np

In [2]:
### pandas is for data manipulation and analysis

In [3]:
### two data types
### >>> series 
### >>>  Dataframe

In [9]:
x = ['deji','mrs ade','mr james','mr philip'] ## list of name

In [10]:
arr = np.array(x) ## coverting name list to numpy array
arr

array(['deji', 'mrs ade', 'mr james', 'mr philip'], dtype='<U9')

In [14]:
ser = pd.Series(x,name="users") ### converting name list to pandas series
ser

0         deji
1      mrs ade
2     mr james
3    mr philip
Name: users, dtype: object

In [17]:
amount = [10,20,30,40] ### list of numbers

In [19]:
ser1 = pd.Series(amount,name="salary")

In [20]:
ser1

0    10
1    20
2    30
3    40
Name: salary, dtype: int64

In [21]:
ser1.size

4

In [22]:
ser1.shape

(4,)

In [23]:
ser1.mean()

25.0

In [24]:
ser1.median()

25.0

In [25]:
ser1.mode()

0    10
1    20
2    30
3    40
Name: salary, dtype: int64

In [26]:
ser1.var()

166.66666666666666

In [27]:
ser1.std()

12.909944487358056

In [31]:
ser1.describe()

count     4.000000
mean     25.000000
std      12.909944
min      10.000000
25%      17.500000
50%      25.000000
75%      32.500000
max      40.000000
Name: salary, dtype: float64

In [32]:
ser1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: salary
Non-Null Count  Dtype
--------------  -----
4 non-null      int64
dtypes: int64(1)
memory usage: 164.0 bytes


In [33]:
### Dataframe

In [42]:
ser1.to_numpy() ### converting series to numpy 

array([10, 20, 30, 40], dtype=int64)

In [43]:
arr2 = ser1.to_numpy() ### assigning it to variable name 

In [45]:
arr2

array([10, 20, 30, 40], dtype=int64)

In [46]:
arr2.reshape((2,2)) ### reshaping to 2 x 2

array([[10, 20],
       [30, 40]], dtype=int64)

In [48]:
arr3 = arr2.reshape((2,2)) ## storing it to a variable name 
arr3

array([[10, 20],
       [30, 40]], dtype=int64)

In [50]:
### 
pd.DataFrame(arr3 , columns = ["amount1" , "amount2"]) ### use dataframe because its more than one columns

,amount1,amount2
0,10,20
1,30,40


In [52]:
### dataframe and how to read csv and other file with pandas 